name: Homework

on:
    workflow_dispatch:
      inputs:
        sample-text:
          description: 'Sample test for test'
          required: true
jobs:

    INPUTTEXT:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - name: 1. Copy bash script
          run: |
            cp ./scripts/homework.sh ./.github/actions/homework/homework.sh
        - name: 2. Run bash script
          uses: ./.github/actions/homework
          with:
            sample-text: ${{ github.event.inputs.sample-text }}
        - name: 3 Download artifact
          uses: actions/upload-artifact@v2
          with:
              name: sample-text.txt
              path: /home/runner/work/devops-school/devops-school/sample-text.txt
